spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/family_budget
    username: usr
    password: usr
  flyway:
    enabled: true

telegram:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

schedule:
  periodic-rule: "0 * * * * *"
  duty: "0 * * * * *"
  todo-reminder: "0 0 8 * * *"